version: '2'
services:
    db:
      image: kddc/dbaas_db:latest
      build:
        context: .
        dockerfile: Dockerfile_db
      volumes:
        - ./postgres:/var/lib/postgresql/data
    web:
      image: kddc/dbaas_web:latest
      build: .
      command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
      volumes:
        - .:/myapp
      ports:
        - "${PORT}:${PORT}"
      depends_on:
        - db
