# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8edfc21acaf5d0e354a761db97ed0b29aa4c0bca882b1d888f08ead38bed51ce0af545835a6378a42c90fcb995872d9fe780c228907dbb9302fe08dff8d289

test:
  secret_key_base: 92afd25a8d83885844bd291ec2ac872efe86475f9b41aa1e082ee8156c63b5937788a2495b35e38ace973431b65f2267e0190b15a997d35729f891556e3a0397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
